"""
app.py
──────
Streamlit front-end for the CV RAG pipeline.

Features
────────
• Upload one or more CV PDFs (drag-and-drop or browse).
• Automatic deduplication via SHA-256 file hash — re-uploading the same
  file is a no-op (Qdrant is not touched again).
• Ask free-text questions about all indexed CVs or filter by candidate.
• Answers are generated by the Azure OpenAI LLM in generator.py.

Run
───
    streamlit run app.py
"""

from __future__ import annotations

import os
import tempfile
from typing import Optional

import streamlit as st

# ── Page config (must be first Streamlit call) ─────────────────────────────
st.set_page_config(
    page_title="CV Intelligence",
    page_icon="📄",
    layout="wide",
)

# ── Project imports ────────────────────────────────────────────────────────
from ingestion.ingest import ingest_cvs
from rag.retrieval import load_chunks_from_qdrant, build_bm25_index
from rag.pipeline import retrieve_pipeline
from generator import generate_answer
from db.qdrant_client import is_filename_indexed


# ══════════════════════════════════════════════════════════════════════════
#  Session-state helpers
# ══════════════════════════════════════════════════════════════════════════

def _init_session():
    if "bm25_index" not in st.session_state:
        st.session_state.bm25_index = None
    if "messages" not in st.session_state:
        st.session_state.messages = []
    if "known_candidates" not in st.session_state:
        st.session_state.known_candidates = []


def _refresh_bm25():
    """Reload all chunks from Qdrant and rebuild the BM25 index."""
    with st.spinner("Refreshing search index…"):
        chunks = load_chunks_from_qdrant()
        st.session_state.bm25_index = build_bm25_index(chunks)

        # Collect unique candidate names for the filter dropdown
        names = sorted({c["candidate_name"] for c in chunks if c["candidate_name"]})
        st.session_state.known_candidates = names


# ══════════════════════════════════════════════════════════════════════════
#  CV Upload — sidebar
# ══════════════════════════════════════════════════════════════════════════

def render_sidebar():
    with st.sidebar:
        st.title("📂 Upload CVs")
        st.caption("Supported format: PDF")

        uploaded_files = st.file_uploader(
            label="Choose PDF files",
            type=["pdf"],
            accept_multiple_files=True,
            label_visibility="collapsed",
        )

        if uploaded_files:
            new_files     = []   # list of (temp_path, original_name)
            skipped_files = []

            for uf in uploaded_files:
                if is_filename_indexed(uf.name):
                    skipped_files.append(uf.name)
                    continue

                file_bytes = uf.read()
                tmp = tempfile.NamedTemporaryFile(
                    delete=False, suffix=".pdf", prefix="cv_"
                )
                tmp.write(file_bytes)
                tmp.close()
                new_files.append((tmp.name, uf.name))

            if skipped_files:
                with st.expander(f"⏭ {len(skipped_files)} already indexed", expanded=True):
                    for name in skipped_files:
                        st.write(f"• {name}")

            if new_files:
                st.info(f"Indexing {len(new_files)} new CV(s)…")
                progress = st.progress(0)
                try:
                    ingest_cvs(new_files)
                    progress.progress(100)
                    st.success(f"✅ Indexed: {', '.join(n for _, n in new_files)}")
                    _refresh_bm25()
                except Exception as e:
                    st.error(f"Ingestion failed: {e}")
                finally:
                    for tmp_path, _ in new_files:
                        try:
                            os.unlink(tmp_path)
                        except OSError:
                            pass

        # ── Index status ───────────────────────────────────────────────
        st.divider()

        if st.button("🔄 Refresh Index", use_container_width=True):
            _refresh_bm25()
            st.success("Index refreshed.")

        if st.session_state.known_candidates:
            st.markdown("**Indexed Candidates**")
            for name in st.session_state.known_candidates:
                st.write(f"• {name}")
        else:
            st.caption("No CVs indexed yet.")


# ══════════════════════════════════════════════════════════════════════════
#  Q&A — main panel
# ══════════════════════════════════════════════════════════════════════════

def render_chat(candidate_filter: Optional[str]):
    st.subheader("💬 Ask About Candidates")

    # Display conversation history
    for msg in st.session_state.messages:
        with st.chat_message(msg["role"]):
            st.markdown(msg["content"])

    # Input box
    if question := st.chat_input("e.g. Who has the most Python experience?"):
        # Guard: index must exist
        if st.session_state.bm25_index is None or st.session_state.bm25_index.get("bm25") is None:
            st.warning(
                "No CVs are indexed yet. Please upload at least one CV first."
            )
            return

        # Add user message to history
        st.session_state.messages.append({"role": "user", "content": question})
        with st.chat_message("user"):
            st.markdown(question)

        # Retrieve + Generate
        with st.chat_message("assistant"):
            with st.spinner("Searching CVs…"):
                try:
                    results = retrieve_pipeline(
                        question=question,
                        bm25_index=st.session_state.bm25_index,
                        candidate_name=candidate_filter or None,
                    )
                    answer = generate_answer(
                        question=question,
                        context_chunks=results,
                        candidate_name=candidate_filter or None,
                    )
                except Exception as e:
                    answer = f"⚠️ Error during retrieval: {e}"

            st.markdown(answer)

            # Expandable sources
            if results:
                with st.expander("📎 Source Chunks", expanded=False):
                    for item in results:
                        chunk = item.get("chunk", {})
                        st.markdown(
                            f"**{chunk.get('candidate_name', '?')}** — "
                            f"*{chunk.get('section', '')}*  "
                            f"`score: {item.get('hybrid_score', 0):.4f}`"
                        )
                        st.caption(chunk.get("text", ""))
                        st.divider()

        st.session_state.messages.append({"role": "assistant", "content": answer})


# ══════════════════════════════════════════════════════════════════════════
#  Main layout
# ══════════════════════════════════════════════════════════════════════════

def main():
    _init_session()

    # Lazy-load BM25 index on first visit (picks up any previously indexed CVs)
    if st.session_state.bm25_index is None:
        _refresh_bm25()

    render_sidebar()

    # ── Header ────────────────────────────────────────────────────────────
    st.title("📄 CV Intelligence Platform")
    st.caption("Upload candidate CVs, then ask questions in natural language.")

    # ── Candidate filter ──────────────────────────────────────────────────
    candidate_options = ["All candidates"] + st.session_state.known_candidates
    selected = st.selectbox(
        "Filter by candidate (optional)",
        options=candidate_options,
        index=0,
    )
    candidate_filter = None if selected == "All candidates" else selected

    st.divider()
    render_chat(candidate_filter)

    # ── Clear chat history ────────────────────────────────────────────────
    if st.session_state.messages:
        if st.button("🗑 Clear Chat", key="clear"):
            st.session_state.messages = []
            st.rerun()


if __name__ == "__main__":
    main()